id: P010779
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20537
  title: སྲིད་པའི་གླུ་ཆུང་ཁྲོམ་པ་དགྱེས་པའི་དགའ་སྟོན།
  author: ''
  volumes:
    dfb535dde6094bf1bb6e4abe24c6eba5:
      image_group_id: I8LS20539
      title: ''
      volume_number: 1
      total_pages: 301
